### PR TITLE
Adds rtr_dlsym() to cache function ptrs

### PR DESCRIPTION
**Pull request by drystone**
This addresses issue #47 which should improve performance as well as avoiding infinite dlsym() loop

### CODE REVIEW

**Comment by erikbor** [comment]
John, can you resolve the merge conflicts against the current master please? Thanks!

**Comment by drystone** [comment]
@erikbor - do you think this is worthwhile? The lookup table is going to be much faster than dlsysm but it does mean a new member has to be added to the enum in common.h and a new lookup for each function hook in common.c ?

Also, I don't understand why the real_{func} variables are all global - although it does no harm as they will always contain the same value, it's unusual practice - especially as they are defined in header files.
I'd rather see local vars eg.

`rtr_fileno_t real_fileno = RETRACE_GET_REAL(fileno);`

**Comment by erikbor** [comment]
@efiop @riataman can you please share your thoughts on this? thanks!

**Comment by riataman** [comment]
As much as it would be nice to avoid a centralized registry of functions, I'm running into a deadlock that this would probably fix. I'm trying to launch firefox under retrace and I'm running into this.

For some reason the call from strcpy->dlsym gets into an error and that causes it to call into our tapped getenv which calls dlsym too, and since we are already in the middle of a call to dlsym this dies.

I can't duplicate this  by calling strcpy myself, so there's something else fishy going on, but I think this change (once updated again ...) would probably fix this.

#0  __lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007ffff79be4af in _L_lock_1081 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007ffff79be428 in __GI___pthread_mutex_lock (mutex=0x555555771750)
    at ../nptl/pthread_mutex_lock.c:134
#3  0x0000555555567cc9 in ?? ()
#4  0x0000555555568e2d in calloc ()
#5  0x00007ffff77b1640 in _dlerror_run (operate=operate@entry=0x7ffff77b1130 <dlsym_doit>,
    args=args@entry=0x7fffffffbf60) at dlerror.c:141
#6  0x00007ffff77b1198 in __dlsym (handle=<optimized out>, name=<optimized out>) at dlsym.c:70
#7  0x00007ffff7bd40b8 in getenv (envname=0x55555556bdaa "MALLOC_OPTIONS") at env.c:49
#8  0x0000555555567d76 in ?? ()
#9  0x0000555555568e2d in calloc ()
#10 0x00007ffff77b1640 in _dlerror_run (operate=operate@entry=0x7ffff77b1130 <dlsym_doit>,
    args=args@entry=0x7fffffffd080) at dlerror.c:141
#11 0x00007ffff77b1198 in __dlsym (handle=<optimized out>, name=<optimized out>) at dlsym.c:70
#12 0x00007ffff7bd86f6 in strcpy (s1=0x7fffffffd11d "firefox-esr", s2=0x55555556acbb "libxul.so")
    at str.c:155
#13 0x0000555555558ca3 in _start ()

**Comment by erikbor** [comment]
Ok John, please go ahead with this.

Thanks

**Comment by drystone** [comment]
I've avoided a centralised function by extending the existing macros to wrap a statically stored function pointer.

The global real_{func} pointers are no longer available so we need to use locals.

It is possible two threads could simultaneously set the cached pointer but this should be harmless as I've used the __atomic family to avoid the possibility of reading half pointers.

**Pull request closed without merging**
