### PR TITLE
Retrace v2 (WIP)

### PR DESCRIPTION
**Pull request by ronaldtse**
Thanks to @ikolomi .

### CODE REVIEW

**Comment by ikolomi** [comment]
Hi guys.
I am well aware of the syntax issues and will address them in near future.
There are tons of more critical stuff that requires attention - fix for
BSDs and Mac for example. I probably will deliver syntax fixes together
with with those, so we will be able to have out alpha release.

**Comment by ronaldtse** [comment]
Since the code is already done but only failing `checkpatch` in the imported `parson` JSON library, I suggest we merge this PR first by disabling `checkpatch` for `parson.{c,h}`.

We can consider switching to `json-c` later on in a separate PR.

Thoughts?

**Comment by ronaldtse** [comment]
@ikolomi would you be able to add an exception to `checkpatch` to merge this first? Thanks.

**Comment by ikolomi** [comment]
Ill be glad to, where i canfind the codebase that travis runs?

**Comment by ronaldtse** [comment]
It’s in this repository itself — `.travis.yml`

**Comment by ikolomi** [comment]
Yes, I see it, will do today

**Comment by ronaldtse** [comment]
Thank you @ikolomi !

**Comment by ikolomi** [comment]
My pleasure!

**Pull request merged**
