### PR TITLE
Issue 66

### PR DESCRIPTION
**Pull request by jjr840430**
- Added umask, mkfifio functions (stat function was already added)
- Moved opendir, closedir functions into dir.c and modify them

### CODE REVIEW

**Comment by jjr840430** [comment]
@erikbor The check for this pulling request was failed, I think it caused since I moved opendir, closedir functions into dir.c/dir.h files.

**Comment by jjr840430** [comment]
@erikbor Can you check this page?
Do I need to solve conflicts before pull requests?

**Comment by erikbor** [comment]
Hi Jin,
Yes please fix the conflicts. Much appreciated.
Thanks.

**Comment by jjr840430** [comment]
@erikbor I fixed issues while checking, I think you can merge this branch. Thanks.

**Comment by erikbor** [comment]
Thanks Jin

**Pull request merged**
