### PR TITLE
fixed config parser

### PR DESCRIPTION
**Pull request by jjr840430**

### CODE REVIEW

**Comment by jjr840430** [comment]
@drystone I changed get_config() function. It seems have some issue while using STAILQ functions.
I converted to use linked list for config parsing.

**Comment by jjr840430** [comment]
@erikbor Can you test stringinjector function in this branch? It would be worked on MacOS.
Now I'm checking issues from Travis CI checker.

**Comment by erikbor** [comment]
@jjr840430 I did a quick test and it works beautifully:
```
(24546) sendto(0 [connected[172.217.24.36:80]], 0x7fff5f931300, 12, 0xc00000000, 0, ) = 12
	0000000	 7465 7374 4141 4141 7465 7374                     | testAAAAtest
(24546) send(0 [connected[172.217.24.36:80]], 0x7fff5f931300, 12, ) = 12 [[redirected]] [fuzzing seed: 1502790944]
	0000000	 7465 7374 4141 4141 7465 7374                     | testAAAAtest
(24546) memcpy(0x7fff4e000a00, 0x1002cefa6, 5, ) = 0x7fff4e000a00
sent
```

I can't test any further right but I will do so tomorrow.

Many thanks for fixing this!!!

**Comment by jjr840430** [comment]
Thanks, @erikbor

**Comment by drystone** [comment]
@jjr840430 It would be preferable to find the config bug rather than to rewrite get_config
- STAILQ is recommended rather than roll-your-own linked lists. <queue.h> rocks
- config lines are now limited length where previously they could be any length
- I suspect [#237](https://github.com/riboseinc/retrace/issues/237) or something like is reintroduced (the test/config.c `(r != 0)` was correct as far as I'm aware, the 4th `config-test2` read should return 0 (there are only 3 in the file)
Is there any chance you can isolate the bug and fix it. I suspect the config parser was already working and the OS X problem is related to some other heap/stack corruption.

**Comment by jjr840430** [comment]
@drystone 

The configuration for 'config-test2' have only 3 lines, so 4-th calling of rtr_get_config_multiple will return 0.
So I think rtr_get_config_multiple() function didn't work properly so far.

Also, Mac OS didn't call runtests.sh when launching Travis CI build. i.e. it didn't test config parser unit test so far.
Here is the link to show it.
https://travis-ci.org/riboseinc/retrace/jobs/264688734

STAILQ is good solution to manipulate the queue list.
However, I think we don't need to use it, as long as we won't use several complex queue operations.
Also the functions for STAILQ may contain several syscall APIs such as malloc, memcpy, free.
So it's not prefer way than using linked list.

I think, if the size of configuration line is 512, then it's enough.
There is no use to have a very long configuration.

If my thoughts are wrong, then let me know.

**Comment by drystone** [comment]
@jjr840430 thanks for your consideration.

Yes, you a quite right, the 4th call to rtr_get_config_multiple() should (and did) return 0. Thats why the test originally failed when non-zero (`FAIL(r != 0`). Now it is broken and loops through the list indefinitely. You've fixed this by adding `if (!config) break;` throughout the codebase. So now we've a test to break on return from get_config_multiple and another before calling it again ie. the behaviour of get_config_multiple is markedly different and we now need to remember to add the additional test after processing each config line (that's code smell IMHO).

Nice one for spotting the MacOS tests weren't working. I hope the Mac folks will be able to remedy this.

I think you may be wrong about queue.h - it's simply macros to manipulate pointers and its use is recommended in [our coding guidelines.](https://www.freebsd.org/cgi/man.cgi?query=style&sektion=9) (and Mac is BSD based so really should have it right!)

And regarding the line length - yes 512 bytes seems ample but why impose an arbitrary limit when there's really no need?

Do you think the MacOS bug that this is addressing is really fixed or do you think it's still lurking somewhere ... I suspect we'll never know because we don't know what caused it :)

**Comment by jjr840430** [comment]
@erikbor @drystone OK, I will try fix as you mentioned. Thanks.

**Pull request closed without merging**
