### PR TITLE
add http server fuzzing example

### PR DESCRIPTION
**Pull request by erikbor**
Example to demonstrate how retrace can be used to fuzz http servers

### CODE REVIEW

**Comment by ronaldtse** [comment]
Style problems.

```
5e4b3ff add http server fuzzing example
ERROR: trailing whitespace
#101: FILE: examples/http-server-overflow/README.md:83:
+> $
ERROR: trailing whitespace
#109: FILE: examples/http-server-overflow/README.md:91:
+< $
ERROR: trailing whitespace
#149: FILE: examples/http-server-overflow/README.md:131:
+$ echo "stringinject,INJECT_BUF_OVERFLOW,send|sendto,1024:3,1" >> /tmp/retrace.conf $
ERROR: trailing whitespace
#192: FILE: examples/http-server-overflow/README.md:174:
+> $
ERROR: trailing whitespace
#206: FILE: examples/http-server-overflow/README.md:188:
+$ /tmp/http-server $
ERROR: open brace '{' following function definitions go on the next line
#239: FILE: examples/http-server-overflow/http-server.c:14:
+int
+main() {
ERROR: spaces required around that '=' (ctx:VxV)
#245: FILE: examples/http-server-overflow/http-server.c:20:
+	char http[256]="HTTP/1.1 302 Found\nContent-Length: 35\n\n<html><body><p>hi</p></body></html>";
 	              ^
ERROR: trailing whitespace
#246: FILE: examples/http-server-overflow/http-server.c:21:
+   $
WARNING: please, no spaces at the start of a line
#246: FILE: examples/http-server-overflow/http-server.c:21:
+   $
ERROR: code indent should use tabs where possible
#248: FILE: examples/http-server-overflow/http-server.c:23:
+   ^Iif (sockbind < 0) {$
WARNING: please, no space before tabs
#248: FILE: examples/http-server-overflow/http-server.c:23:
+   ^Iif (sockbind < 0) {$
WARNING: please, no spaces at the start of a line
#248: FILE: examples/http-server-overflow/http-server.c:23:
+   ^Iif (sockbind < 0) {$
ERROR: trailing whitespace
#252: FILE: examples/http-server-overflow/http-server.c:27:
+   $
WARNING: please, no spaces at the start of a line
#252: FILE: examples/http-server-overflow/http-server.c:27:
+   $
ERROR: trailing whitespace
#255: FILE: examples/http-server-overflow/http-server.c:30:
+   $
WARNING: please, no spaces at the start of a line
#255: FILE: examples/http-server-overflow/http-server.c:30:
+   $
ERROR: trailing whitespace
#259: FILE: examples/http-server-overflow/http-server.c:34:
+   $
WARNING: please, no spaces at the start of a line
#259: FILE: examples/http-server-overflow/http-server.c:34:
+   $
ERROR: trailing whitespace
#264: FILE: examples/http-server-overflow/http-server.c:39:
+      $
WARNING: please, no spaces at the start of a line
#264: FILE: examples/http-server-overflow/http-server.c:39:
+      $
ERROR: trailing whitespace
#273: FILE: examples/http-server-overflow/http-server.c:48:
+   $
WARNING: please, no spaces at the start of a line
#273: FILE: examples/http-server-overflow/http-server.c:48:
+   $
ERROR: trailing whitespace
#290: FILE: examples/http-server-overflow/http-server.c:65:
+   $
WARNING: please, no spaces at the start of a line
#290: FILE: examples/http-server-overflow/http-server.c:65:
+   $
ERROR: trailing whitespace
#296: FILE: examples/http-server-overflow/http-server.c:71:
+      $
WARNING: please, no spaces at the start of a line
#296: FILE: examples/http-server-overflow/http-server.c:71:
+      $
total: 16 errors, 10 warnings, 274 lines checked
NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.
NOTE: Whitespace errors detected.
      You may wish to use scripts/cleanpatch or scripts/cleanfile
Your patch has style problems, please review.

```

**Comment by ronaldtse** [comment]
@jjr840430 would you be able to help clean up this code for PR? Thanks!

**Comment by jjr840430** [comment]
@ronaldtse I'm now away from my dev machine.

I will clean up this code tomorrow. Thanks.

**Comment by ronaldtse** [comment]
That's fantastic, thanks @jjr840430 !

**Comment by jjr840430** [comment]
@ronaldtse @erikbor Fixed coding style issues.

**Comment by erikbor** [comment]
@jjr840430 thanks!

**Comment by ronaldtse** [comment]
Thanks @jjr840430 !

**Pull request merged**
