### PR TITLE
Malloc fuzzing

### PR DESCRIPTION
**Pull request by riataman**
Put in a setting to fail a percentage of malloc/realloc/calloc calls.

### CODE REVIEW

**Comment by ronaldtse** [comment]
Thank you @riataman , this is real fast!

**Comment by ronaldtse** [comment]
@efiop @drystone are we OK to merge this?

**Comment by efiop** [comment]
@ronaldtse I'm waiting for @riataman to resolve conflicts.

**Comment by ronaldtse** [comment]
Just wanted to add that @catap has fixed a whole slew of bugs using retrace memory fuzzing in riboseinc/rnp@0eb838ff. First real use of retrace. Woohoo!

**Comment by riataman** [comment]
Awesome! I hereby declare @catap user number zero. Cheers!

**Pull request merged**
