### PR TITLE
An initial delivery of the cli framework.

### PR DESCRIPTION
**Pull request by ikolomi**
The framework allows an extendable menu to be created by retrace modules
and accessed by an user from a terminal emulator.
The framework interface is defined in retrace_cli.h,
it provides functionalities such as registering of commands and printf/scanf primitives.
In addition in order to facilitate initialization of modules and
specifically of the cli framework, a constructor function was added in retrace_main.c,
which will be called before the process main() function.
As an example, the constructor defines two menu commands: "Say Hi" and "Terminate"
Modules are expected to build upon that foundation.
Tested with minicom on Ubuntu Linux.

### CODE REVIEW

**Comment by ronaldtse** [comment]
@ikolomi thank you for the enhancement! Agree with @jjr840430 .

Hopefully this puts us on a good path to a programmable retrace.

**Comment by ikolomi** [comment]
Guys, I took note that the jenkins-testing.ribose.com fails to respond constantly when trying to open Details of the build...
Can someone take a look?

**Comment by ronaldtse** [comment]
@ikolomi :wink: the Jenkins host is actually behind VPN, but the results are generally same as Travis. It seems that there are some remaining code style checks — you can actually run checkpatch locally — if you’re on brew look for our homebrew checkpatch formula, or on CentOS/RHEL look for our checkpatch RPM.

**Comment by ronaldtse** [comment]
```
WARNING: Block comments use a trailing */ on a separate line
#216: FILE: src/retrace_cli.c:227:
+		 * */
ERROR: open brace '{' following function declarations go on the next line
#310: FILE: src/retrace_main.c:50:
+static void cmd_func_hello(void) {
ERROR: open brace '{' following function declarations go on the next line
#316: FILE: src/retrace_main.c:54:
+static void cmd_func_exit(void) {
ERROR: open brace '{' following function declarations go on the next line
#326: FILE: src/retrace_main.c:65:
+static void *cli_thread(void *x_void_ptr) {
ERROR: open brace '{' following function declarations go on the next line
#334: FILE: src/retrace_main.c:71:
+static void retrace_main(void) {
total: 4 errors, 1 warnings, 319 lines checked
```

**Comment by ronaldtse** [comment]
I've fixed the remaining styling issues, let's merge it first and add documentation.

**Comment by ronaldtse** [comment]
Thanks @ikolomi !

**Comment by ikolomi** [comment]
My pleasure, working on the doc, will deliver soon

**Pull request merged**
