### PR TITLE
Load configuration via environment variable 'RETRACE_CONFIG_VAR'

### PR DESCRIPTION
**Pull request by jjr840430**
Implemented issue #334

### CODE REVIEW

**Comment by jjr840430** [comment]
@drystone I think it would be better to modify the configuration of `retrace` at run-time.
Then is it possible to use the wrapper script in this case?

**Comment by drystone** [comment]
@jjr840430 , no it won't be possible to modify config from the script.

I think it would be better to avoid the temporary file creation - you either have to create a temporary file with no way of deleting or use a predefined path (~/.something) that can cause problems if you have more than one instance of `retrace`.

How about modifying `get_config` to add the config from the environment to the config list and then load the config file as before, adding to the list?

It's moot anyway as config is about to receive a major overhaul.

**Comment by ikolomi** [comment]
Guys,
Agree with @drystone . To summarize:
- IMHO, config via env should not replace the config via file, but complement
- Why to create the temporary file in the first place?  The config setup can be as following:

1. look for the configuration env. variable. if exists parse and setup config, done
2. look for the file configuration env. variable. if exists parse the file and setup config, done
3. Use the default config, done

**Comment by jjr840430** [comment]
Agreed, guys.
I didn't regard the case of multiple instances of retrace. Thanks for your advice.

**Comment by erikbor** [comment]
@jjr840430 sorry I didn't have time earlier to review this. I agree that a temporary file is not the best way because that currently can be done outside of Retrace. Moving that into Retrace itself does not improve things.

And I also agree with configuration setup flow that @ikolomi described.

**Comment by ronaldtse** [comment]
@erikbor @jjr840430 are we ready to merge this?

**Comment by jjr840430** [comment]
@ronaldtse I need to modify something here. I will let you know after doing.

**Comment by jjr840430** [comment]
Currently `retrace` is parsing the configurations based on `file pointer`, so it needs to convert the most part of config parsing.
If we need to have new config by JSON, then this pull request may be ignored.

**Pull request merged**
