### PR TITLE
Fixed rtr_get_multiple_config() usage

### PR DESCRIPTION
**Pull request by jjr840430**
related with issue #237

### CODE REVIEW

**Comment by jjr840430** [comment]
@drystone Can you solve this problem? I think it's fast way that you fix that. :)

**Comment by drystone** [comment]
@jjr840430 does this work for you - and does it still work on mac?

**Comment by jjr840430** [comment]
@drystone Thanks for your help. I will test and let you know soon. Thanks.

**Comment by jjr840430** [comment]
@drystone Not working on mac os.
Here is the log.

config(31584,0x7fff999ab3c0) malloc: *** malloc was initialized without entropy
../retrace: line 68: 31584 Bus error: 10           RETRACE_CONFIG=../retrace.conf.example DYLD_FORCE_FLAT_NAMESPACE=1 DYLD_INSERT_LIBRARIES=../src/.libs/libretrace.dylib ./config
FAIL runtests.sh (exit status: 138)

**Comment by drystone** [comment]
@jjr840430 that's annoying! Unfortunately I'm away until next week. Can we put a hold on this until Monday?

**Comment by jjr840430** [comment]
@drystone OK, no problem.

**Comment by ronaldtse** [comment]
@drystone @jjr840430 looks like it works on macOS now? Ready to merge?

**Comment by jjr840430** [comment]
@ronaldtse I'm waiting for @drystone 's change.

**Comment by drystone** [comment]
Well it's passing the tests and the loop bug is fixed so might as well merge ... thanks @jjr840430 for the mods and your patience

**Pull request merged**
