### PR TITLE
-f option overide RETRACE_CONFIG

### PR DESCRIPTION
**Pull request by catap**

### CODE REVIEW

**Comment by riataman** [comment]
Merged, thanks.

**Comment by catap** [comment]
@wizzard but with your way `retrace -f /path/to/config ...` doesn't work on OS X that I'm using.

**Comment by wizzard** [comment]
@catap the current code causes test apps crash on MacOS when `retrace.conf.example` file is used.
I disabled conf file, please see `retrace.in` file "XXX" comment.

**Comment by riataman** [comment]
@wizzard the tests where crashing because the config file is specifying malloc fuzzing which macOS doesn't like since it uses it internally. It was working before because the -f option was basically no working in macOS. The solution is not to break -f again, but disable the malloc fuzzying option.

**Comment by wizzard** [comment]
Ok, so then we need 2 different config files for our test apps with and w/o malloc fuzzing?

**Comment by riataman** [comment]
Just comment the malloc fuzzing option for now. Not sure what would it take to make it work in macOS. Maybe delay the fuzzing until main has already run somehow?

You can open a new issue for that.

**Comment by catap** [comment]
@riataman looks like OSX has a bug inside DYLD and it never check that malloc may return NULL :)

So, for test proposal it's better to comment, yes.

**Comment by riataman** [comment]
Yeah, what a pain :) in Linux glibc almost never uses the public facing functions internally which is great for retrace as we avoid noise and this kind of bugs. 

On macOS they do use them and its a pain in the arse since there's a lot of noise even before main() is called would need to investigate if something can be done at some point about that.

**Pull request merged**
