### PR TITLE
New RPC version

### PR DESCRIPTION
**Pull request by drystone**
New and improved ... less functionality but better structured. The back end shims send a `CALL_INIT` message to the front end and then polls for messages from the front end which can be used to peek and poke parameters/memory/return values and environment. The front end can setup the pre-call redirects, trigger the `real_function`, set up the post-call redirects and cause the shim to return with a `CALL_COMPLETE` message. Each thread/process in the back end has a dedicated socket with which to communicate with the front end, the front end is single threaded and uses `select()` to wait for messages. There is therefore no need for further synchronisation in the back end whose concurrent messages are handled sequentially by the front end. Currently very rudimentary but can now be extended to cater for most, if not all, of the current retrace feature set. Please review.
```
./configure --enable-rpc
make
cd rpc
./retrace /bin/ls
```

### CODE REVIEW

**Comment by ronaldtse** [comment]
@drystone failed at style check:

```
4d45d10 Merge 6cbd123b46cffb323c74fa933c92450482db4387 into a961bc7c98e01d18e69be7c553fa4e55d6e5200d
ERROR: space required after that close brace '}'
#189: FILE: rpc/backend.c:107:
+	    { (char *)rpc_version, 32 }};

ERROR: space required after that close brace '}'
#517: FILE: rpc/frontend.c:52:
+		{version, 32}};

WARNING: please, no space before tabs
#1050: FILE: rpc/functions2yaml.c:50:
+^I{"pid_t",^I"pid_t ",^I^INULL^I ^I},$

WARNING: please, no space before tabs
#1053: FILE: rpc/functions2yaml.c:53:
+^I{"pstring",^I"char **",^I^INULL^I ^I},$

ERROR: that open brace { should be on the previous line
#1422: FILE: rpc/rpc.c:39:
+	struct iovec iov[] =
+	    {{&msg_type, sizeof(msg_type)}, {(void *)buf, length}};

ERROR: space required after that close brace '}'
#1422: FILE: rpc/rpc.c:39:
+	    {{&msg_type, sizeof(msg_type)}, {(void *)buf, length}};

ERROR: that open brace { should be on the previous line
#1557: FILE: rpc/rpc.c:54:
+	struct iovec iov[] =
+	    {{msg_type, sizeof(*msg_type)}, {(void *)buf, RPC_MSG_LEN_MAX}};

ERROR: space required after that close brace '}'
#1557: FILE: rpc/rpc.c:54:
+	    {{msg_type, sizeof(*msg_type)}, {(void *)buf, RPC_MSG_LEN_MAX}};

total: 6 errors, 2 warnings, 1765 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

Your patch has style problems, please review.
```

**Comment by erikbor** [comment]
@drystone when making on macOS I get the following error:

```sh
$ make
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in src
  CC       libretrace_la-char.lo
  CC       libretrace_la-common.lo
  CC       libretrace_la-dir.lo
  CC       libretrace_la-dlopen.lo
  CC       libretrace_la-env.lo
  CC       libretrace_la-exec.lo
  CC       libretrace_la-exit.lo
  CC       libretrace_la-file.lo
  CC       libretrace_la-fork.lo
  CC       libretrace_la-httpredirect.lo
  CC       libretrace_la-id.lo
  CC       libretrace_la-log.lo
  CC       libretrace_la-malloc.lo
  CC       libretrace_la-netdb.lo
  CC       libretrace_la-netfuzz.lo
  CC       libretrace_la-perror.lo
  CC       libretrace_la-pipe.lo
  CC       libretrace_la-pledge.lo
  CC       libretrace_la-popen.lo
  CC       libretrace_la-printf.lo
  CC       libretrace_la-read.lo
  CC       libretrace_la-scanf.lo
  CC       libretrace_la-select.lo
  CC       libretrace_la-sock.lo
  CC       libretrace_la-str.lo
  CC       libretrace_la-strinject.lo
  CC       libretrace_la-temp.lo
temp.c:229:17: warning: 'tempnam' is deprecated: This function is provided for compatibility reasons only. Due to security concerns inherent in the design of tempnam(3), it is
      highly recommended that you use mkstemp(3) instead. [-Wdeprecated-declarations]
RETRACE_REPLACE(tempnam, char *, (const char *dir, const char *pfx), (dir, pfx))
                ^
/usr/include/stdio.h:397:7: note: 'tempnam' has been explicitly marked deprecated here
char    *tempnam(const char *__dir, const char *__prefix) __DARWIN_ALIAS(tempnam);
         ^
temp.c:229:17: warning: 'tempnam' is deprecated: This function is provided for compatibility reasons only. Due to security concerns inherent in the design of tempnam(3), it is
      highly recommended that you use mkstemp(3) instead. [-Wdeprecated-declarations]
RETRACE_REPLACE(tempnam, char *, (const char *dir, const char *pfx), (dir, pfx))
                ^
/usr/include/stdio.h:397:7: note: 'tempnam' has been explicitly marked deprecated here
char    *tempnam(const char *__dir, const char *__prefix) __DARWIN_ALIAS(tempnam);
         ^
temp.c:287:17: warning: 'tmpnam' is deprecated: This function is provided for compatibility reasons only. Due to security concerns inherent in the design of tmpnam(3), it is
      highly recommended that you use mkstemp(3) instead. [-Wdeprecated-declarations]
RETRACE_REPLACE(tmpnam, char *, (char *s), (s))
                ^
/usr/include/stdio.h:277:7: note: 'tmpnam' has been explicitly marked deprecated here
char    *tmpnam(char *);
         ^
temp.c:287:17: warning: 'tmpnam' is deprecated: This function is provided for compatibility reasons only. Due to security concerns inherent in the design of tmpnam(3), it is
      highly recommended that you use mkstemp(3) instead. [-Wdeprecated-declarations]
RETRACE_REPLACE(tmpnam, char *, (char *s), (s))
                ^
/usr/include/stdio.h:277:7: note: 'tmpnam' has been explicitly marked deprecated here
char    *tmpnam(char *);
         ^
4 warnings generated.
  CC       libretrace_la-time.lo
  CC       libretrace_la-trace.lo
  CC       libretrace_la-write.lo
  CCLD     libretrace.la
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libretrace.a(libretrace_la-pledge.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libretrace.a(libretrace_la-pledge.o) has no symbols
Making all in test
make[2]: Nothing to be done for `all'.
Making all in tools
Making all in stringinjector
  CC       stringinjector.o
  CCLD     stringinject
make[3]: Nothing to be done for `all-am'.
Making all in rpc
  CC       functions2yaml.o
functions2yaml.c:28:10: fatal error: 'error.h' file not found
#include <error.h>
         ^
1 error generated.
make[2]: *** [functions2yaml.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

I suppose you can soon debug this on your own mac :)

**Comment by ronaldtse** [comment]
@erikbor that's strange because the build passed on macOS Jenkins 😉 

As you probably know the `tempnam` warnings were intended to support a deprecated function.

**Comment by ronaldtse** [comment]
Ahhh that's why it passed on Jenkins macOS:
```
checking whether to enable rpc... no
```

**Comment by ronaldtse** [comment]
@drystone maybe RPC should always be enabled unless explicitly disabled?

**Comment by drystone** [comment]
@erikbor I've not tested PRC on Mac yet. Though I'm looking forward to getting the opportunity :)

@ronaldtse indeed, it wouldn't hurt to enable the rpc build by default - it has no effect on the the main retrace. I'll do it as soon as I've got Mac compatibility sorted.

**Comment by ronaldtse** [comment]
@drystone in this case could you enable it by default in this PR so it could build in macOS automatically?

I suppose we need some tests to ensure RPC functionality doesn't get broken in upcoming changes.

**Comment by ronaldtse** [comment]
@drystone thanks for the updates -- could we also enable rpc by default so the test build includes it?

**Comment by drystone** [comment]
@ronaldtse will do with the next push ... probably tomorrow :+1:

**Comment by ronaldtse** [comment]
@drystone Nice stuff. @erikbor probably wants to mess with the RPC universe, too (as in injecting extra bytes) 😉

**Comment by ronaldtse** [comment]
Builds failing here:
```
/bin/bash ../libtool  --tag=CC   --mode=link gcc -Wall -Wno-sizeof-array-argument -I/home/travis/builds/cmocka-install/include  -L/home/travis/builds/cmocka-install/lib -o functions2yaml functions2yaml.o  -lpthread -ldl 
libtool: link: gcc -Wall -Wno-sizeof-array-argument -I/home/travis/builds/cmocka-install/include -o functions2yaml functions2yaml.o  -L/home/travis/builds/cmocka-install/lib -lpthread -ldl
./functions2yaml <functions.txt >functions.yaml
mustache - shim_c.template <functions.yaml >shim.c
/bin/bash: mustache: command not found
make[2]: *** [shim.c] Error 127
make[2]: Leaving directory `/home/travis/build/riboseinc/retrace/rpc'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/travis/build/riboseinc/retrace'
make: *** [all] Error 2
```

**Comment by drystone** [comment]
@ronaldtse - ha, well I think we'd all like to see some improvements in the universe :)

There's a build depends on `ruby-mustache`. I'm not sure whether it'll remain that way ... there's a C version we might want to include somewhere in the src tree. Meantime I'll add a quick fix to the CI.

**Comment by ronaldtse** [comment]
@drystone yeah maybe we could try https://github.com/x86-64/mustache-c for this.

**Comment by drystone** [comment]
@ronaldtse can you pass me some output from the Jenkins build please.

Mustache: Thanks for the link - I'll look into this today.

**Comment by ronaldtse** [comment]
@drystone it's just failing here, nothing new:
```sh
mustache - shim_c.template <functions.yaml >shim.c
/bin/sh: mustache: command not found
make[2]: *** [shim.c] Error 127
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

Do you want me to install `mustache` on Jenkins for it to work?

**Comment by drystone** [comment]
@ronaldtse mustache again! Yes, please do install on Jenkins. `gem install mustache` works for linux, osx and OpenBSD at least.

I've looked at a couple of C implementations - the one you [linked above](https://github.com/x86-64/mustache-c) seems portable but requires callbacks for filling template fields (doesn't natively handle json/yaml) so would require some work to create a suitable `mustache` executable. And [this one](https://gitlab.com/jobol/mustach) which is more complete but won't compile on mac. Either way it's going to be more code to maintain so I think we should stick with the Ruby version for the time being. Perhaps we can explore other code generation utilities such as XSLT in the future.

**Pull request merged**
