### PR TITLE
Add a bunch of new functions and tests for them.

### PR DESCRIPTION
**Pull request by efiop**

### CODE REVIEW

**Comment by ronaldtse** [comment]
@efiop Let me get @erikbor to review this. We should get Travis working soon so the build actually succeeds 👍

**Comment by efiop** [comment]
Sorry, I didn't add travis yet(currently working on it). This pull request is manually tested with live examples and unittests.

**Comment by efiop** [comment]
Added simple travis script to at least run through unit tests.

**Comment by ronaldtse** [comment]
Thanks @efiop !

**Pull request merged**
